plugins {
  id 'java'
  id 'org.springframework.boot' version '3.1.5'
  id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

group = 'com.checkout'
version = '0.0.1-SNAPSHOT'

java {
  sourceCompatibility = '17'
}

repositories {
  mavenCentral()
}

ext {
  set('testcontainers.version', "1.19.8")
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

  implementation 'net.logstash.logback:logstash-logback-encoder:8.1'

  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.assertj:assertj-core:3.27.7'
  testImplementation 'org.mockito:mockito-core:5.23.0'
  testImplementation 'org.wiremock:wiremock-standalone:3.13.2'
  testImplementation "org.testcontainers:junit-jupiter"
}

tasks.named('test') {
  useJUnitPlatform()
  // RYUK tends to be problematic on Apple Silicon so disabling for TestContainers
  environment 'TESTCONTAINERS_RYUK_DISABLED', 'true'
}
