services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:2525"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  gateway:
      container_name: gateway
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8090:8090"
      environment:
        - BANK_BASE_URL=http://bank_simulator:8080
        - SERVER_PORT=8090
      depends_on:
        bank_simulator:
          condition: service_healthy
      networks:
        - payment-network

networks:
  payment-network:
    driver: bridge