server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

logging.level.com.checkout=INFO

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

bank.base-url=http://localhost:8080
payment.allowed-currencies=GBP,EUR,USD